import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Schedule from '@/components/Schedule'

class Topic {
  constructor(title, startDate) {
    this.title = title
    this.startDate = startDate
    this.lastReviewed = startDate
    this.EF = 2.5 //default value
    this.repetitions = 0
    this.intervals = []
  }

  next() {
    const newDate = new Date(this.lastReviewed)
    const days = this.intervals.at(-1) || 0
    newDate.setDate(newDate.getDate() + days)
    return newDate
  }
}

const schedule = [
  new Topic('HTML Fundamentals', new Date()),
  new Topic('CSS Fundamentals', new Date()),
  new Topic('Identify notes on treble cleff', new Date()),
]

function AddTopic() {
  return <></>
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome, Broh
        </h1>

        <Schedule schedule={schedule}/>
        <AddTopic />
        
      </main>
    </div>
  )
}
